/**
 * Created by kevin on 12/29/16.
 */


const pickupLines =  [

    "Did it hurt when you fell from heaven? Cause obviously you landed on your face",
    "Is your name Daniel? Cause DAMN!",
    "You know what’s beautiful? Read the first word.",
    "Do you have a name or can I call you mine?",
    "Are you flappy bird? Cause I could tap you all night",
    "I hope you got a pet insurance, cause tonight I’m gonna destroy that pussy.",
    "Guess what I’m wearing? The smile you gave me!",
    "Is your dad retarded? Because you’re special",
    "Call me leaves, cause you should be blowing me.",
    "Can I follow you? Cause my mom told me to follow my dreams",
    "Do you know your ABC’s? Cause I wanna give you the 4th letter of the alphabet.",
    "I’m asian so I’ll eat your cat",
    "Roses are red, violets are blue, lava is hot and so are you.",
    "If I was an octopus, all my 3 hearts would beat for you .",
    "Is there a cellphone in your backpocket? Cause that ass is calling me!",
    "If Internet Explorer is brave enough to ask you to be your default browser, I’m brave enough to ask you out!",
    "Didn’t You Wear That Yesterday?",
    "Your eyes are as blue as the sea I dumped my ex’s body in.",
    "I’m willing to lower my standards if you’re going on a date with me.",
    "Damn Girl is your name Wifi ? Because I’m feeling a connection!",
    "I should call you Google, because you have everything I’m looking for.",
    "You Sexy, You Fine. I Really Wanna Make You Mine.",
    "Are you made out of grapes? Because you are fine as wine!",
    "You are almost as hot as my mom.",
    "You work at a post office? Cause I saw you checking out my package.",
    "How much does it cost to date you? Cause damn, you look expensive!",
    "Your Face [Pause] I like that shit!",
    "Are you a tortilla? Because I want to flip you over and eat you out!",
    "You look exactly like my future ex-wife.",
    "Did you die recently? Cause girl, you look like an angel to me.",
    "I know where they give out free drinks. [Where?] My House!",
    "You’d be so much more cute if you had my money. [whatever she replies] Sorry I don’t date gold diggers!",
    "I might be ugly but I’ll treat you right!",
    "I just want to tell you that you’re really beautiful [pause] but I’m gay.",
    "You dropped something! What? (Point at the ground) Your standards.",
    "There are 8 planets in the universe, but only 7 after I destroy Uranus",
    "Can you touch me? I want to tell my friends I was touched by an Angel.",
    "You look like my mom!",
    "I saw you girls from over there and just want to let you know that I’m taken.",
    "When I was walking by, I noticed you stalking so.. what’s up?",
    "You wanna know what’s big? (Pause) My house you weirdo!",
    "I just wanna let you know how beautiful you are and was wondering if you could buy me a drink?",
    "I heard you’re good in algebra, can you replace my X without asking Y",
    "Aside from being sexy, what do you do for a living?",
    "I’ll treat you like my homework: Slam you on the table and do you all night long!",
    "Your mom told me to say “Hi” to you",
    "I named my dick “the truth” cause bitches can’t handle it!",
    "I must be hunting treasure because I’m digging your chest",
    "She: I’m in a relationship | You: Let’s talk about how we can get you out of that.",
    "My mom thinks I`m gay, can you help me prove her wrong?",
    "Is Your Dad A Preacher? Cause Girl You’re A Blessing",
    "Do you believe in karma? Because I know some good karma-sutra positions.",
    "The letter ‘X’ scares me [Why?] Because I never want to be yours.",
    "Is that a mirror in your pocket? Cause I can see myself in your pants!",
    "Your so cute its distracting",
    "You know why I am like a squirrel? Cause I want to bury my nuts in you.",
    "Roses are red violets are blue I didn’t know what perfect was until I met you",
    "You dropped something! [What?] Your smile",
    "You are hotter than the bottom of my laptop.",
    "I might not go down in history, but I’ll go down on you!",
    "I want you to be the girl who takes my virginity.",
    "I’m no organ donor but I’d be happy to give you my heart.",
    "You look familiar, didn’t we take a class together? I could’ve sworn we had chemistry.",
    "Can I buy you a drink or do you prefer cash?",
    "Smile, if you want to have sex with me.",
    "You look fabulous! [pause] for your age.",
    "I like every bone in your body, especially mine.",
    "You’re so fucking sexy! You look just like my mom.",
    "Damn Girl, you’re cute, let me get your email address.",
    "I`m no weatherman, but you can expect a few inches tonight.",
    "You know what I like in a girl? [What?] My dick.",
    "I don’t believe in love at first sight, but I’m willing to make an exception in your case",
    "I don’t really believe in love at first sight, until I saw you.",
    "Damn Girl, your ass is bigger than my future!",
    "There’s only one thing I want to change about you. Your last name.",
    "If I were a cat i’d spend all 9 lives with you.",
    "Of all your beautiful curves, your smile is my favourite.",
    "Are you a vampire? Cause you looked a little thirsty when you looked at me.",
    "Are you a magician? Because whenever I look at you everyone else disappears.",
    "I’m feeling a little bit off today, but you definitely turned me on.",
    "If you were a basketball, I’d never shoot. [Why?] Because I’d always miss you.",
    "Do you have a band aid? Cause I scrapped my knees falling for you.",
    "Pizza is my second favourite thing to eat in bed.",
    "Go between two black girls and say “Let’s make an Orio!”",
    "Are you religios? Cause you’re the answer to all my prayers.",
    "I’m in a Boyband called Wrong Direction.",
    "My friends bet I can’t talk to the prettiest girl. Wanna use their money to buy drinks?",
    "You know how I got these guns? [Point to biceps] Lifting children out of poverty.",
    "Do you want to have good sex? [No!] Well then come to my place!",
    "Let’s play Barbie. I’ll be Ken and you can be the box I come in.",
    "I used to be a Gambler, but then I realized that all I needed was the Queen of my Heart",
    "Call me Chris Brown, cause I’d hit that! [Look at her ass]",
    "Your body is 75% water, and I’m thirsty.",
    "Can I punch you in the face.. [pause] ..with my lips?",
    "You know why they call me the cat whisperer? Cause I know exactly what that pussy needs.",
    "You have eyes like spanners. When I look in to them, my nuts tighten.",
    "(Take a photo of her) I want to show my mom what my next girlfriend looks like",
    "I have to show you the prettiest girl I’ve ever seen. (show phone with frontcam)",
    "Hey, tie your shoes! I don’t want you falling for anyone else.",
    "You’re on my list of things to do tonight.",
    "You’re like Pringles once I pop you, I can’t stop you.",
    "You’re like my own personal brand of heroin.",
    "You’re like my little toe, because I’m going to bang you on every piece of furniture in my home.",
    "Your so hot I could roast my meat on you, baby.",
    "Your smile lit up the room, so I just had to come over.",
    "Your shirt has to go, but you can stay.",
    "Your place or mine? Tell you what? I’ll flip a coin. Head at my place, tail at yours.",
    "Your lips look so lonely…Would they like to meet mine?",
    "Your eyes are really cute. Oh, wait! I think the right one is a little cuter than the left one.",
    "Your eyes are blue, like the ocean. And baby, I’m lost at sea.",
    "Your eyes are as blue as window cleaner.",
    "Your eyes are as blue as my toilet water at home.",
    "Your daddy must be a drug dealer, cuz you’re dope.",
    "Your ass is so nice that it is a shame that you have to sit on it.",
    "You’d mind if I fantasize about you?",
    "You, me, handcuffs, and whipped cream: interested?",
    "You smell… We should go take a shower together.",
    "You look like trash, may I take you out?",
    "You should stop drinking! (Why?) Because you are driving me home.",
    "You should join the circus.(Why?) So you can learn to juggle my balls all day.",
    "You Say: I’m jealous of your dress. She says “Why?” You say: Because it’s touching your body, and I’m not.",
    "Sorry, I can’t hold on… I’ve already fallen for you.",
    "You say, “So, did you here the one about the guy and the girl who had the most sexual relationship?” The reply, “No”. You respond, “Well then, let’s go to my place and I’ll tell you all about it.”",
    "You remind me of my dead ex-girlfriend.",
    "You remind me of my cousin. (How?) I want to fuck you so bad, but I know that I can’t.",
    "You really shouldn’t wear makeup. You’re messing with perfection!",
    "You owe me a drink, you’re so ugly I dropped mine when I saw you.",
    "You MUST have a nice personality.",
    "You must be Jelly, cause jam don’t shake like that.",
    "You must be Jamaican, because Jamaican me crazy.",
    "You must be a hell of a thief because you stole my heart from across the room.",
    "You might not be the best looking girl here, but beauty is only a light switch away.",
    "You may fall from the sky, you may fall from a tree, but the best way to fall… is in love with me.",
    "You make me wish I weren’t gay!",
    "You make me want to calibrate my joystick without the latest drivers.",
    "You look so innocent, you look so sweet, as long as I have a face, you will always have a seat.",
    "You look familiar, have we had sex before?",
    "You look cold. Want to use me as a blanket?",
    "You like sleeping? Me too! We should do it together sometime.",
    "You might be asked to leave soon. You are making the other women look bad.",
    "You know, sweetie, my lips won’t just kiss themselves…",
    "You know, if I were you, I’d have sex with me.",
    "You know, I would die happy if I saw you naked just once!",
    "You know, I wanna go inside your wine cabinet and pull myself out a stiff one.",
    "You know, Dr. Phil says I’m afraid of commitment…Want to help prove him wrong?",
    "You know you’re in love when you can’t fall asleep because reality is finally better than your dreams.",
    "You know what material this is? [Grab your shirt] Boyfriend material.",
    "You know the more I drink, the prettier you get!",
    "You know how your hair would look really good? [No.] In my lap.",
    "You know how some men buy really expensive cars to make up for certain shortages? Well, I don’t even own a car."

];