/**
 * Created by kevin on 12/29/16.
 */

module.exports = {
    pickupLines: [

        "There are 8 planets in the universe, but only 7 after I destroy Uranus",
        "Did it hurt when you fell from heaven? Cause obviously you landed on your face",
        "Is your name Daniel? Cause DAMN!",
        "You know what’s beautiful? Read the first word.",
        "Do you have a name or can I call you mine?",
        "Are you flappy bird? Cause I could tap you all night",
        "I hope you got a pet insurance, cause tonight I’m gonna destroy that pussy.",
        "Guess what I’m wearing? The smile you gave me!",
        "Is your dad retarded? Because you’re special",
        "Call me leaves, cause you should be blowing me.",
        "Can I follow you? Cause my mom told me to follow my dreams",
        "Do you know your ABC’s? Cause I wanna give you the 4th letter of the alphabet.",
        "I’m asian so I’ll eat your cat",
        "Roses are red, violets are blue, lava is hot and so are you.",
        "If I was an octopus, all my 3 hearts would beat for you .",
        "Is there a cellphone in your backpocket? Cause that ass is calling me!",
        "If Internet Explorer is brave enough to ask you to be your default browser, I’m brave enough to ask you out!",
        "Didn’t You Wear That Yesterday?",
        "Your eyes are as blue as the sea I dumped my ex’s body in.",
        "I’m willing to lower my standards if you’re going on a date with me.",
        "Damn Girl is your name Wifi ? Because I’m feeling a connection!",
        "I should call you Google, because you have everything I’m looking for.",
        "You Sexy, You Fine. I Really Wanna Make You Mine.",
        "Are you made out of grapes? Because you are fine as wine!",
        "You are almost as hot as my mom.",
        "You work at a post office? Cause I saw you checking out my package.",
        "How much does it cost to date you? Cause damn, you look expensive!",
        "Your Face [Pause] I like that shit!",
        "Are you a tortilla? Because I want to flip you over and eat you out!",
        "You look exactly like my future ex-wife.",
        "Did you die recently? Cause girl, you look like an angel to me.",
        "I know where they give out free drinks. [Where?] My House!",
        "You’d be so much more cute if you had my money. [whatever she replies] Sorry I don’t date gold diggers!",
        "I might be ugly but I’ll treat you right!",
        "I just want to tell you that you’re really beautiful [pause] but I’m gay.",
        "You dropped something! What? (Point at the ground) Your standards.",
        "There are 8 planets in the universe, but only 7 after I destroy Uranus",
        "Can you touch me? I want to tell my friends I was touched by an Angel.",
        "You look like my mom!",
        "I saw you girls from over there and just want to let you know that I’m taken.",
        "When I was walking by, I noticed you stalking so.. what’s up?",
        "You wanna know what’s big? (Pause) My house you weirdo!",
        "I just wanna let you know how beautiful you are and was wondering if you could buy me a drink?",
        "I heard you’re good in algebra, can you replace my X without asking Y",
        "Aside from being sexy, what do you do for a living?",
        "I’ll treat you like my homework: Slam you on the table and do you all night long!",
        "Your mom told me to say “Hi” to you",
        "I named my dick “the truth” cause bitches can’t handle it!",
        "I must be hunting treasure because I’m digging your chest",
        "She: I’m in a relationship | You: Let’s talk about how we can get you out of that.",
        "My mom thinks I`m gay, can you help me prove her wrong?",
        "Is Your Dad A Preacher? Cause Girl You’re A Blessing",
        "Do you believe in karma? Because I know some good karma-sutra positions.",
        "The letter ‘X’ scares me [Why?] Because I never want to be yours.",
        "Is that a mirror in your pocket? Cause I can see myself in your pants!",
        "Your so cute its distracting",
        "You know why I am like a squirrel? Cause I want to bury my nuts in you.",
        "Roses are red violets are blue I didn’t know what perfect was until I met you",
        "You dropped something! [What?] Your smile",
        "You are hotter than the bottom of my laptop.",
        "I might not go down in history, but I’ll go down on you!",
        "I want you to be the girl who takes my virginity.",
        "I’m no organ donor but I’d be happy to give you my heart.",
        "You look familiar, didn’t we take a class together? I could’ve sworn we had chemistry.",
        "Can I buy you a drink or do you prefer cash?",
        "Smile, if you want to have sex with me.",
        "You look fabulous! [pause] for your age.",
        "I like every bone in your body, especially mine.",
        "You’re so fucking sexy! You look just like my mom.",
        "Damn Girl, you’re cute, let me get your email address.",
        "I`m no weatherman, but you can expect a few inches tonight.",
        "You know what I like in a girl? [What?] My dick.",
        "I don’t believe in love at first sight, but I’m willing to make an exception in your case",
        "I don’t really believe in love at first sight, until I saw you.",
        "Damn Girl, your ass is bigger than my future!",
        "There’s only one thing I want to change about you. Your last name.",
        "If I were a cat i’d spend all 9 lives with you.",
        "Of all your beautiful curves, your smile is my favourite.",
        "Are you a vampire? Cause you looked a little thirsty when you looked at me.",
        "Are you a magician? Because whenever I look at you everyone else disappears.",
        "I’m feeling a little bit off today, but you definitely turned me on.",
        "If you were a basketball, I’d never shoot. [Why?] Because I’d always miss you.",
        "Do you have a band aid? Cause I scrapped my knees falling for you.",
        "Pizza is my second favourite thing to eat in bed.",
        "Go between two black girls and say “Let’s make an Orio!”",
        "Are you religios? Cause you’re the answer to all my prayers.",
        "I’m in a Boyband called Wrong Direction.",
        "My friends bet I can’t talk to the prettiest girl. Wanna use their money to buy drinks?",
        "You know how I got these guns? [Point to biceps] Lifting children out of poverty.",
        "Do you want to have good sex? [No!] Well then come to my place!",
        "Let’s play Barbie. I’ll be Ken and you can be the box I come in.",
        "I used to be a Gambler, but then I realized that all I needed was the Queen of my Heart",
        "Call me Chris Brown, cause I’d hit that! [Look at her ass]",
        "Your body is 75% water, and I’m thirsty.",
        "Can I punch you in the face.. [pause] ..with my lips?",
        "You know why they call me the cat whisperer? Cause I know exactly what that pussy needs.",
        "You have eyes like spanners. When I look in to them, my nuts tighten.",
        "(Take a photo of her) I want to show my mom what my next girlfriend looks like",
        "I have to show you the prettiest girl I’ve ever seen. (show phone with frontcam)",
        "Hey, tie your shoes! I don’t want you falling for anyone else.",
        "You’re on my list of things to do tonight.",
        "You’re like Pringles once I pop you, I can’t stop you.",
        "You’re like my own personal brand of heroin.",
        "You’re like my little toe, because I’m going to bang you on every piece of furniture in my home.",
        "Your so hot I could roast my meat on you, baby.",
        "Your smile lit up the room, so I just had to come over.",
        "Your shirt has to go, but you can stay.",
        "Your place or mine? Tell you what? I’ll flip a coin. Head at my place, tail at yours.",
        "Your lips look so lonely…Would they like to meet mine?",
        "Your eyes are really cute. Oh, wait! I think the right one is a little cuter than the left one.",
        "Your eyes are blue, like the ocean. And baby, I’m lost at sea.",
        "Your eyes are as blue as window cleaner.",
        "Your eyes are as blue as my toilet water at home.",
        "Your daddy must be a drug dealer, cuz you’re dope.",
        "Your ass is so nice that it is a shame that you have to sit on it.",
        "You’d mind if I fantasize about you?",
        "You, me, handcuffs, and whipped cream: interested?",
        "You smell… We should go take a shower together.",
        "You look like trash, may I take you out?",
        "You should stop drinking! (Why?) Because you are driving me home.",
        "You should join the circus.(Why?) So you can learn to juggle my balls all day.",
        "You Say: I’m jealous of your dress. She says “Why?” You say: Because it’s touching your body, and I’m not.",
        "Sorry, I can’t hold on… I’ve already fallen for you.",
        "You say, “So, did you here the one about the guy and the girl who had the most sexual relationship?” The reply, “No”. You respond, “Well then, let’s go to my place and I’ll tell you all about it.”",
        "You remind me of my dead ex-girlfriend.",
        "You remind me of my cousin. (How?) I want to fuck you so bad, but I know that I can’t.",
        "You really shouldn’t wear makeup. You’re messing with perfection!",
        "You owe me a drink, you’re so ugly I dropped mine when I saw you.",
        "You MUST have a nice personality.",
        "You must be Jelly, cause jam don’t shake like that.",
        "You must be Jamaican, because Jamaican me crazy.",
        "You must be a hell of a thief because you stole my heart from across the room.",
        "You might not be the best looking girl here, but beauty is only a light switch away.",
        "You may fall from the sky, you may fall from a tree, but the best way to fall… is in love with me.",
        "You make me wish I weren’t gay!",
        "You make me want to calibrate my joystick without the latest drivers.",
        "You look so innocent, you look so sweet, as long as I have a face, you will always have a seat.",
        "You look familiar, have we had sex before?",
        "You look cold. Want to use me as a blanket?",
        "You like sleeping? Me too! We should do it together sometime.",
        "You might be asked to leave soon. You are making the other women look bad.",
        "You know, sweetie, my lips won’t just kiss themselves…",
        "You know, if I were you, I’d have sex with me.",
        "You know, I would die happy if I saw you naked just once!",
        "You know, I wanna go inside your wine cabinet and pull myself out a stiff one.",
        "You know, Dr. Phil says I’m afraid of commitment…Want to help prove him wrong?",
        "You know you’re in love when you can’t fall asleep because reality is finally better than your dreams.",
        "You know what material this is? [Grab your shirt] Boyfriend material.",
        "You know the more I drink, the prettier you get!",
        "You know how your hair would look really good? [No.] In my lap.",
        "You know how some men buy really expensive cars to make up for certain shortages? Well, I don’t even own a car.",
        "Is your name Google? Because you have everything I've been searching for.",
        "You make my software turn into hardware!",
        "Is your name Wi-fi? Because I'm really feeling a connection.",
        "Are you sitting on the F5 key? Cause your ass is refreshing.",
        "Want to see my HARD Disk? I promise it isn't 3.5 inches and it ain't floppy.",
        "You can put a Trojan on my Hard Drive anytime.",
        "You still use Internet Explorer? You must like it nice and slow.",
        "I hope you're an ISO file, because I'd like to mount you.",
        "My servers never go down... but I do!",
        "My 'up-time' is better than BSD.",
        "Are you an angel, because your texture mapping is divine!",
        "You've stolen the ASCII to my heart.",
        "Are you a computer keyboard? Because you're my type.",
        "You got me stuck on Caps Lock, if you know what I mean.",
        "If you were a web browser, you'd be called a Fire-foxy lady.",
        "How about we do a little peer-to-peer saliva swapping?",
        "Mind if I run a sniffer to see if your ports are open?",
        "Your beauty rivals the graphics of Call of Duty.",
        "You must be Windows 95 because you've got me feeling so unstable.",
        "I was hoping you wouldn't block my pop-up.",
        "Want to see my Red Hat?",
        "If you won't let me buy you a drink, at least let me fix your laptop.",
        "You put the SPARC in my workstation.",
        "You're so pretty, I wouldn't even need to use an Instagram filter if I took your photo.",
        "Isn't your e-mail address beautifulgirl@mydreams.com?",
        "I'd switch to emacs for you.",
        "What's a nice girl like you doing in a chatroom like this?",
        "No, that's not a Logitech MX-100 in my pants, but thanks for noticing.",
        "Nice Set of Floppies!",
        "I think you could be an integral part of my project life cycle.",
        "If you have an empty slot, I have the card to fill it.",
        "WebMD says your love is contagious.",
        "Hey, how 'bout I take off your cover and insert a bigger CPU.",
        "I'd like to play on your laptop.",
        "Where's the 'like' button for that smile?",
        "You totally spiked my traffic.",
        "You are the Apple of my i-Mac.",
        "If you were an ISP I'd dial you all day long.",
        "If you were an ebay auction, I'd totally 'buy it now'.",
        "You have a trojan? hmm... I think I'll need to take a look at that backdoor.",
        "Come to my 127.0.0.1 and I’ll give you sudo access.",
        "I must be using Apple maps, because I keep getting lost in your eyes.",
        "I'd get a T3 to watch your streaming video.",
        "I'll bet my hard drive is the biggest you've ever seen.",
        "Your homepage or mine?",
        "Hey Baby, Let me hack your kernel.",
        "No, that's not an iPod mini in my pocket. I'm just happy to see you.",
        "You auto-complete me.",
        "I didn't mean to ogle you, but I'd sure like to Google you.",
        "I was wondering if you'd like to go back to My-Space, so I can Twitter with your Yahoo, until I Google all over your Facebook?",
        "If you ever need to get rid of a trojan, don't hesitate to call me!",
        "You're making me feel like I have something in common with these pop-up ads.",
        "What's the difference between a crush and a Facebook account? [what?] I'm not rapidly developing a Facebook account on you.",
        "I need to hop over to Facebook for a second to change my status to smitten.",
        "Roses are #ff0000, violets are #0000ff, all my base are belong to you.",
        "Need me to unzip your files?",
        "Are your pants a compressed file? Because I'd love to unzip them!",
        "I googled your name earlier... I clicked on 'I'm Feeling Lucky.'",
        "How about we go home and you handle my exception?",
        "If we were connected on Linkedin, I'd endorse you all night long.",
        "I wish you were Broadband, so I could get high-speed access.",
        "Girl, you are hotter than the bottom of my laptop.",
        "I'd ask if you come here often, but I already stalk you on FourSquare.",
        "Can I do a penetration test on your back door?",
        "Can you put a Trojan on my Hard Drive?",
        "Hey girl, can you sit on my laptop?",
        "Can I stick my flash drive in your USB port?",
        "Computer techs have skilled fingers if you know what I mean.",
        "I wish I was your derivative so I could lie tangent to your curves.",
        "My love for you is like a concave up function because it is always increasing.",
        "How can I know so many hundreds of digits of pi and not the 7 digits of your phone number?",
        "I wish I was your second derivative so I could investigate your concavities.",
        "You and I would add up better than a Riemann sum.",
        "Hey baby, what's your sine?",
        "I need a little help with my Calculus, can you integrate my natural log?",
        "By looking at you I can tell you're 36-25-36, which by the way are all perfect squares.",
        "You fascinate me more than the Fundamental Theorem of Calculus.",
        "Are you a 90 degree angle? 'Cause you are looking right!",
        "My love for you is like pi... never ending.",
        "I'd like to plug my solution into your equation.",
        "Since distance equals velocity times time, let's let velocity and time approach infinity, because I want to go all the way with you.",
        "I am equivalent to the Empty Set when you are not with me.",
        "I don’t like my current girlfriend. Mind if I do a you-substitution?",
        "I can figure out the square root of any number in less than 10 seconds. What? You don’t believe me? Well, then, let’s try it with your phone number.",
        "Hey, baby want to Squeeze my Theorem while I poly your nomial?",
        "Hey...nice asymptote.",
        "I'm not being obtuse, but you're acute girl.",
        "I don't know if you're in my range, but I'd sure like to take you back to my domain.",
        "Are you a 45 degree angle? Because you're acute-y.",
        "My love for you is like y=2^x... exponentially growing.",
        "I'll take you to your limit if you show me your end behavior.",
        "Can I explore your mean value?",
        "The derivative of my love for you is 0, because my love for you is constant.",
        "I'm good at math... let's add a bed, subtract our clothes, divide your legs, and multiply!",
        "Our love is like dividing by zero... you cannot define it.",
        "If you were a graphics calculator, I'd look at your curves all day long!",
        "I've been secant you for a long time.",
        "If I'm sine and you're cosine, wanna make like a tangent?",
        "Meeting you is like making a switch to polar coordinates: complex and imaginary things are given a magnitude and a direction.",
        "Being without you is like being a metric space in which exists a cauchy sequence that does not converge.",
        "My love for you is a monotonically increasing unbounded function",
        "You are the solution to my homogeneous system of linear equations.",
        "I heard you're good at algebra - Could you replace my X without asking Y?",
        "Are you a math teacher? Because you got me harder than calculus.",
        "I'll take you to the limit as X approaches infinity.",
        "Your name is Leslie? Look, I can spell your name on my calculator!",
        "Let's take each other to the limit to see if we converge",
        "You must be the square root of two because I feel irrational around you.",
        "Let me integrate our curves so that I can increase our volume",
        "If i were a function you would be my asymptote - I always tend towards you.",
        "Your beauty cannot be spanned by a finite basis of vectors.",
        "I wish I was your problem set, because then I'd be really hard, and you'd be doing me on the desk.",
        "My love is like an exponential curve - it's unbounded",
        "My love for you is like a fractal - it goes on forever.",
        "My love for you is like the derivative of a concave up function because it is always increasing. we're going to assume this concave up function resembles x^2 so that slopes is actually increasing.",
        "I hope you know set theory because I want to intersect and union you",
        "You've got more curves than a triple integral.",
        "Honey, you're sweeter than pi.",
        "If you were sin^2x and I was cos^2x, then together we'd make one.",
        "Baby, you're like a student and I'm like a math book... you solve all my problems!",
        "My friends told me that I should ask you out because you can't differentiate.",
        "Do you need math help? Wanna expand my polynomial?",
        "You must be differentiable, because all I see are smooth curves.",
        "Life without you is like dereferencing a NULL pointer.",
        "I know the spring constant for my mattress. Wanna take some data?",
        "Were your parents engineers? Because you have a nice design.",
        "Wanna dance? I can really put your inertia in motion.",
        "You have cuter dimples than a cardioid!",
        "If I was sin^2 and you were cos^2, together we would be 1.",
        "You are like a high amperage current and I’m a high resistance wire, cause you’ve got me hot.",
        "Nice set of parabolas!",
        "I heard you like roses, so here’s a polar coordinate graph of r=1+cos(theta).",

    ]
};